# ============================================================
# High-impact journal composite figure:
# Gene relevance + pathway relevance
#
# Public-repo version:
# - expects exported summary tables generated by the biology pipeline
# - uses a relative directory by default
#
# Usage:
#   Rscript figure_scripts/figure4_gene_pathway_relevance.R \
#       examples/manuscript_summary_tables/figure4_inputs \
#       outputs/Figure4_gene_pathway_relevance
# ============================================================

library(tidyverse)
library(patchwork)
library(viridis)
library(scales)
library(glue)

args <- commandArgs(trailingOnly = TRUE)
data_dir <- ifelse(length(args) >= 1, args[[1]], "examples/manuscript_summary_tables/figure4_inputs")
out_prefix <- ifelse(length(args) >= 2, args[[2]], "Figure4_gene_and_pathway_relevance")

latent_pattern <- "^latent_gene_table\\.ALL_SAMPLES\\.long_.*\\.csv$"
disgenet_file  <- file.path(data_dir, "consolidated.tsv")
pathway_file_pattern <- "^overlap_terms_by_library_topN_[A-Za-z0-9]+_LD[0-9]+_NS[0-9]+_L[0-9]+\\.csv$"

disease_codes <- c(
  "ALZ","ASD","BD","BMI","BRC","CAD","CD","COL","EOS",
  "HDL","HGT","HT","LDL","LUN","PRC","RA","T1D","T2D"
)

USE_SQRT_TRANSFORM_GENE <- TRUE
FDR_THRESHOLD <- 0.05
USE_NEGLOG10_FDR <- TRUE
CAP_INTENSITY_AT_QUANTILE <- 0.99
MAX_PATHWAYS_TO_SHOW <- 18
MIN_DISEASE_SUPPORT_FOR_PATHWAY <- 1
USE_SHORT_PATHWAY_IDS <- TRUE
SHORT_ID_PREFIX <- "P"
TRUNCATE_LABEL_TO <- 28

theme_journal <- function() {
  theme_minimal(base_size = 12.5, base_family = "sans") +
    theme(
      panel.grid = element_blank(),
      axis.line = element_line(colour = "black", linewidth = 0.45),
      axis.text = element_text(colour = "black", size = 9.8),
      axis.title = element_text(colour = "black", size = 11.5, face = "bold"),
      plot.title = element_text(size = 14.2, face = "bold", hjust = 0, margin = margin(b = 2)),
      plot.subtitle = element_text(size = 9.8, colour = "grey30", hjust = 0, lineheight = 1.02, margin = margin(b = 4)),
      plot.caption = element_text(size = 8.6, colour = "grey30", hjust = 0, lineheight = 1.0, margin = margin(t = 4)),
      legend.title = element_text(size = 10.2, face = "bold"),
      legend.text = element_text(size = 9.5),
      plot.margin = margin(3, 3, 3, 3)
    )
}

disease_map <- tribble(
  ~Disease, ~DisGeNET_term,                ~Mapping_note,
  "ALZ",    "Alzheimer's disease",         "exact",
  "ASD",    "autistic disorder",           "exact",
  "BD",     "bipolar disorder",            "exact",
  "BMI",    "obesity",                     "proxy for BMI trait",
  "BRC",    "breast cancer",               "exact",
  "CAD",    "coronary artery disease",     "exact",
  "CD",     "ulcerative colitis",          "proxy",
  "COL",    "colon cancer",                "proxy",
  "EOS",    "Barrett's esophagus",         "proxy",
  "HDL",    "metabolic syndrome X",        "proxy",
  "HGT",    "osteoporosis",                "proxy",
  "HT",     "hypertension",                "exact",
  "LDL",    "metabolic syndrome X",        "proxy",
  "LUN",    "lung cancer",                 "exact",
  "PRC",    "prostate cancer",             "exact",
  "RA",     "rheumatoid arthritis",        "exact",
  "T1D",    "type 1 diabetes mellitus",    "exact",
  "T2D",    "type 2 diabetes mellitus",    "exact"
)

latent_files <- list.files(path = data_dir, pattern = latent_pattern, full.names = TRUE)
if (length(latent_files) == 0) stop("No latent_gene_table.ALL_SAMPLES.long_*.csv files found in input directory")
if (!file.exists(disgenet_file)) stop("consolidated.tsv not found in input directory")

disgenet_raw <- readr::read_tsv(disgenet_file, show_col_types = FALSE) %>%
  dplyr::transmute(
    doid_name   = trimws(as.character(doid_name)),
    geneSymbol  = toupper(trimws(as.character(geneSymbol))),
    score_max   = suppressWarnings(as.numeric(score_max)),
    score_mean  = suppressWarnings(as.numeric(score_mean))
  ) %>%
  dplyr::filter(!is.na(doid_name), !is.na(geneSymbol), geneSymbol != "")

disgenet_gene_scores <- disgenet_raw %>%
  dplyr::mutate(best_score = pmax(score_max, score_mean, na.rm = TRUE)) %>%
  dplyr::group_by(doid_name, geneSymbol) %>%
  dplyr::summarise(best_score = max(best_score, na.rm = TRUE), .groups = "drop")

disease_gene_scores <- disease_map %>%
  dplyr::inner_join(disgenet_gene_scores, by = c("DisGeNET_term" = "doid_name"))

disease_ref_totals <- disease_gene_scores %>%
  dplyr::group_by(Disease) %>%
  dplyr::summarise(total_disgenet_genes_for_disease = dplyr::n_distinct(geneSymbol), .groups = "drop")

extract_gene_disease_from_filename <- function(path) {
  nm <- basename(path)
  sub("^latent_gene_table\\.ALL_SAMPLES\\.long_([A-Za-z0-9]+)_LD.*$", "\\1", nm)
}

latent_all <- purrr::map_dfr(latent_files, function(f) {
  disease <- extract_gene_disease_from_filename(f)
  readr::read_csv(f, show_col_types = FALSE) %>%
    dplyr::transmute(
      Disease    = disease,
      Latent_Dim = as.character(Latent_Dim),
      LV_num     = as.integer(stringr::str_extract(Latent_Dim, "\\d+")),
      LV_label   = paste0("LV", LV_num + 1),
      GENE       = toupper(trimws(as.character(GENE))),
      Sample     = as.character(Sample),
      SNP_ID     = as.character(SNP_ID)
    )
})

latent_scored <- latent_all %>%
  dplyr::inner_join(disease_map %>% dplyr::select(Disease, DisGeNET_term), by = "Disease") %>%
  dplyr::left_join(disease_gene_scores %>% dplyr::select(Disease, geneSymbol, best_score), by = c("Disease", "GENE" = "geneSymbol"))

latent_gene_unique <- latent_scored %>%
  dplyr::distinct(Disease, LV_num, LV_label, GENE, best_score)

lv_summary <- latent_gene_unique %>%
  dplyr::group_by(Disease, LV_num, LV_label) %>%
  dplyr::summarise(
    n_disgenet_genes = dplyr::n_distinct(GENE[!is.na(best_score)]),
    weighted_signal  = sum(best_score[!is.na(best_score)], na.rm = TRUE),
    mean_signal      = mean(best_score[!is.na(best_score)], na.rm = TRUE),
    .groups = "drop"
  ) %>%
  dplyr::mutate(
    n_disgenet_genes = tidyr::replace_na(n_disgenet_genes, 0),
    weighted_signal  = tidyr::replace_na(weighted_signal, 0),
    mean_signal      = tidyr::replace_na(mean_signal, 0)
  )

all_gene_diseases <- sort(unique(latent_all$Disease))

lv_summary <- lv_summary %>%
  tidyr::complete(
    Disease = all_gene_diseases,
    tidyr::nesting(LV_num, LV_label),
    fill = list(n_disgenet_genes = 0, weighted_signal = 0, mean_signal = 0)
  ) %>%
  dplyr::left_join(disease_ref_totals, by = "Disease")

gene_heat_df <- lv_summary %>%
  dplyr::mutate(
    capture_fraction = ifelse(total_disgenet_genes_for_disease > 0, n_disgenet_genes / total_disgenet_genes_for_disease, 0),
    weighted_fraction = ifelse(total_disgenet_genes_for_disease > 0, weighted_signal / total_disgenet_genes_for_disease, 0),
    heat_value = if (USE_SQRT_TRANSFORM_GENE) sqrt(weighted_fraction) else weighted_fraction
  )

gene_heat_mat <- gene_heat_df %>%
  dplyr::select(Disease, LV_label, heat_value) %>%
  tidyr::pivot_wider(names_from = LV_label, values_from = heat_value) %>%
  dplyr::arrange(Disease)

gene_row_names <- gene_heat_mat$Disease
gene_heat_mat_num <- gene_heat_mat %>% dplyr::select(-Disease) %>% as.matrix()
rownames(gene_heat_mat_num) <- gene_row_names

gene_col_hc <- stats::hclust(stats::dist(t(gene_heat_mat_num)), method = "ward.D2")
gene_col_order <- colnames(gene_heat_mat_num)[gene_col_hc$order]

gene_col_avg <- colMeans(gene_heat_mat_num[, gene_col_order, drop = FALSE], na.rm = TRUE)
if (mean(gene_col_avg[1:min(3, length(gene_col_avg))], na.rm = TRUE) > mean(tail(gene_col_avg, min(3, length(gene_col_avg))), na.rm = TRUE)) {
  gene_col_order <- rev(gene_col_order)
}

gene_row_score_df <- gene_heat_df %>%
  dplyr::group_by(Disease) %>%
  dplyr::summarise(avg_heat = mean(heat_value, na.rm = TRUE), max_heat = max(heat_value, na.rm = TRUE), total_heat = sum(heat_value, na.rm = TRUE), total_genes = sum(n_disgenet_genes, na.rm = TRUE), .groups = "drop") %>%
  dplyr::arrange(avg_heat, max_heat, total_heat, total_genes)

gene_row_order <- gene_row_score_df$Disease
gene_row_order <- c("ASD", setdiff(gene_row_order, "ASD"))

gene_heat_df <- gene_heat_df %>%
  dplyr::mutate(Disease = factor(Disease, levels = gene_row_order), LV_label = factor(LV_label, levels = gene_col_order))

gene_peak_df <- gene_heat_df %>% dplyr::group_by(Disease) %>% dplyr::slice_max(order_by = heat_value, n = 1, with_ties = FALSE) %>% dplyr::ungroup()

gene_heat_df <- gene_heat_df %>%
  dplyr::mutate(
    label_text = ifelse(n_disgenet_genes > 0, as.character(n_disgenet_genes), ""),
    label_color = ifelse(heat_value >= stats::quantile(heat_value, 0.72, na.rm = TRUE), "black", "white")
  )

gene_top_df <- gene_heat_df %>% dplyr::group_by(LV_label) %>% dplyr::summarise(total_relevant_genes = sum(n_disgenet_genes, na.rm = TRUE), .groups = "drop") %>% dplyr::mutate(LV_label = factor(LV_label, levels = gene_col_order))
gene_right_df <- gene_heat_df %>% dplyr::group_by(Disease) %>% dplyr::summarise(total_relevant_genes = sum(n_disgenet_genes, na.rm = TRUE), .groups = "drop") %>% dplyr::mutate(Disease = factor(Disease, levels = gene_row_order))

p_gene_heat <- ggplot2::ggplot(gene_heat_df, ggplot2::aes(x = LV_label, y = Disease, fill = heat_value)) +
  ggplot2::geom_tile(color = "white", linewidth = 0.45) +
  ggplot2::geom_tile(data = gene_peak_df, fill = NA, color = "white", linewidth = 0.95) +
  ggplot2::geom_text(ggplot2::aes(label = label_text, color = label_color), size = 2.7, fontface = "bold", show.legend = FALSE) +
  ggplot2::scale_color_identity() +
  viridis::scale_fill_viridis(option = "magma", direction = 1, name = "Gene relevance\nscore", labels = scales::label_number(accuracy = 0.01)) +
  ggplot2::labs(title = "a  Disease-relevant DisGeNET gene capture across latent variables", subtitle = "Color indicates disease-relevance intensity; numbers are matched disease-relevant genes.", x = "Latent variable", y = "Disease", caption = "Rows progress from lower to higher disease-relevance intensity.") +
  theme_journal() +
  ggplot2::theme(legend.position = "right")

p_gene_top <- ggplot2::ggplot(gene_top_df, ggplot2::aes(x = LV_label, y = total_relevant_genes)) +
  ggplot2::geom_col(width = 0.72, fill = "#666666") +
  ggplot2::geom_text(ggplot2::aes(label = total_relevant_genes), vjust = -0.22, size = 2.8) +
  ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = c(0, 0.10))) +
  ggplot2::labs(title = "b  Total disease-relevant genes captured by latent variable", subtitle = "Summed across diseases.", x = NULL, y = "Matched genes") +
  theme_journal() +
  ggplot2::theme(axis.text.x = ggplot2::element_blank(), axis.ticks.x = ggplot2::element_blank())

p_gene_right <- ggplot2::ggplot(gene_right_df, ggplot2::aes(x = total_relevant_genes, y = Disease)) +
  ggplot2::geom_col(width = 0.72, fill = "#666666") +
  ggplot2::geom_text(ggplot2::aes(label = total_relevant_genes), hjust = -0.08, size = 2.7) +
  ggplot2::scale_x_continuous(expand = ggplot2::expansion(mult = c(0, 0.10))) +
  ggplot2::labs(title = "c  Total disease-relevant genes captured by disease", subtitle = "Summed across latent variables.", x = "Matched genes", y = NULL) +
  theme_journal() +
  ggplot2::theme(axis.text.y = ggplot2::element_blank(), axis.ticks.y = ggplot2::element_blank())

gene_left_block <- p_gene_top / p_gene_heat + patchwork::plot_layout(heights = c(0.82, 1.88))
gene_block <- gene_left_block | p_gene_right + patchwork::plot_layout(widths = c(1.9, 1.05), guides = "collect")

pathway_files <- list.files(path = data_dir, pattern = pathway_file_pattern, full.names = TRUE, recursive = TRUE)
if (length(pathway_files) == 0) {
  stop("No overlap_terms_by_library_topN_<DISEASE>_LD*_NS*_L*.csv files found recursively under input directory")
}

extract_pathway_disease_from_filename <- function(path) {
  nm <- basename(path)
  m <- stringr::str_match(nm, "^overlap_terms_by_library_topN_([A-Za-z0-9]+)_LD[0-9]+_NS[0-9]+_L[0-9]+\\.csv$")
  m[, 2]
}

extract_pathway_config_from_filename <- function(path) {
  nm <- basename(path)
  cfg <- stringr::str_extract(nm, "LD[0-9]+_NS[0-9]+_L[0-9]+")
  ifelse(is.na(cfg), "UNKNOWN_CFG", cfg)
}

normalize_pathway_name <- function(x) {
  x %>% as.character() %>% stringr::str_replace_all("_", " ") %>% stringr::str_replace_all("\\s+", " ") %>% stringr::str_squish()
}

build_display_pathway <- function(library, term) {
  lib_short <- dplyr::case_when(
    stringr::str_detect(tolower(library), "reactome") ~ "REAC",
    stringr::str_detect(tolower(library), "kegg") ~ "KEGG",
    stringr::str_detect(tolower(library), "^go") ~ "GO",
    TRUE ~ as.character(library)
  )
  paste0(lib_short, ": ", normalize_pathway_name(term))
}

shorten_pathway_name <- function(x, width = 28) {
  x %>% stringr::str_replace("^REAC: ", "") %>% stringr::str_replace("^KEGG: ", "") %>% stringr::str_replace("^GO: ", "") %>% stringr::str_trunc(width = width, side = "right", ellipsis = "…")
}

pathway_raw <- purrr::map_dfr(pathway_files, function(f) {
  disease <- extract_pathway_disease_from_filename(f)
  config  <- extract_pathway_config_from_filename(f)
  if (is.na(disease)) return(NULL)
  df <- tryCatch(readr::read_csv(f, show_col_types = FALSE), error = function(e) NULL)
  if (is.null(df) || nrow(df) == 0) return(NULL)
  required_cols <- c("Library", "Term", "BestFDR", "MedianFDR", "MeanFDR", "BestScore", "MedianScore", "MeanScore", "NumSamplesTopN", "NumLVsTopN", "RepRateSamplesTopN", "RepRateLVsTopN")
  missing_cols <- setdiff(required_cols, names(df))
  if (length(missing_cols) > 0) return(NULL)
  df %>%
    dplyr::transmute(
      Disease = disease,
      config = config,
      Library = as.character(Library),
      pathway = build_display_pathway(Library, Term),
      BestFDR = suppressWarnings(as.numeric(BestFDR)),
      MedianFDR = suppressWarnings(as.numeric(MedianFDR)),
      MeanFDR = suppressWarnings(as.numeric(MeanFDR)),
      BestScore = suppressWarnings(as.numeric(BestScore)),
      MedianScore = suppressWarnings(as.numeric(MedianScore)),
      MeanScore = suppressWarnings(as.numeric(MeanScore)),
      NumSamplesTopN = suppressWarnings(as.numeric(NumSamplesTopN)),
      NumLVsTopN = suppressWarnings(as.numeric(NumLVsTopN)),
      RepRateSamplesTopN = suppressWarnings(as.numeric(RepRateSamplesTopN)),
      RepRateLVsTopN = suppressWarnings(as.numeric(RepRateLVsTopN)),
      file = basename(f)
    ) %>%
    dplyr::filter(!is.na(pathway), pathway != "", !is.na(BestFDR), is.finite(BestFDR))
})

if (nrow(pathway_raw) == 0) stop("No usable pathway rows found after reading the files.")

pathway_raw <- pathway_raw %>% dplyr::filter(BestFDR <= FDR_THRESHOLD)
if (nrow(pathway_raw) == 0) stop("No pathway entries passed the chosen FDR threshold.")

pathway_summary <- pathway_raw %>%
  dplyr::group_by(Disease, pathway) %>%
  dplyr::summarise(
    n_configs_hit = dplyr::n_distinct(config),
    best_fdr = min(BestFDR, na.rm = TRUE),
    median_fdr = median(BestFDR, na.rm = TRUE),
    mean_fdr = mean(BestFDR, na.rm = TRUE),
    best_score = max(BestScore, na.rm = TRUE),
    mean_score = mean(MeanScore, na.rm = TRUE),
    max_NumLVsTopN = max(NumLVsTopN, na.rm = TRUE),
    max_NumSamplesTopN = max(NumSamplesTopN, na.rm = TRUE),
    max_RepRateLVsTopN = max(RepRateLVsTopN, na.rm = TRUE),
    max_RepRateSamplesTopN = max(RepRateSamplesTopN, na.rm = TRUE),
    n_libraries = dplyr::n_distinct(Library),
    .groups = "drop"
  )

if (USE_NEGLOG10_FDR) {
  pathway_summary <- pathway_summary %>% dplyr::mutate(fdr_signal = -log10(pmax(best_fdr, 1e-300)))
} else {
  pathway_summary <- pathway_summary %>% dplyr::mutate(fdr_signal = 1 / pmax(best_fdr, 1e-300))
}

pathway_summary <- pathway_summary %>%
  dplyr::mutate(
    support_rate = 0.5 * max_RepRateLVsTopN + 0.5 * max_RepRateSamplesTopN,
    recurrence_factor = log1p(n_configs_hit),
    intensity_raw = fdr_signal * recurrence_factor * pmax(support_rate, 1e-6)
  )

cap_value <- stats::quantile(pathway_summary$intensity_raw, probs = CAP_INTENSITY_AT_QUANTILE, na.rm = TRUE)
pathway_summary <- pathway_summary %>% dplyr::mutate(intensity_capped = pmin(intensity_raw, cap_value))

pathway_rank <- pathway_summary %>%
  dplyr::group_by(pathway) %>%
  dplyr::summarise(global_configs = sum(n_configs_hit, na.rm = TRUE), global_intensity = sum(intensity_capped, na.rm = TRUE), n_diseases = dplyr::n_distinct(Disease), .groups = "drop") %>%
  dplyr::arrange(dplyr::desc(global_intensity), dplyr::desc(global_configs), dplyr::desc(n_diseases), pathway)

top_pathways_multi <- pathway_rank %>% dplyr::filter(n_diseases >= MIN_DISEASE_SUPPORT_FOR_PATHWAY) %>% dplyr::slice_head(n = MAX_PATHWAYS_TO_SHOW) %>% dplyr::pull(pathway)
top_pathways <- if (length(top_pathways_multi) >= 8) top_pathways_multi else pathway_rank %>% dplyr::slice_head(n = MAX_PATHWAYS_TO_SHOW) %>% dplyr::pull(pathway)

path_heat_df <- pathway_summary %>% dplyr::filter(pathway %in% top_pathways)
if (nrow(path_heat_df) == 0) stop("No pathway data remained after pathway selection.")

all_path_diseases <- sort(unique(pathway_summary$Disease))
all_pathways <- unique(top_pathways)

path_heat_df <- tidyr::expand_grid(Disease = all_path_diseases, pathway = all_pathways) %>%
  dplyr::left_join(path_heat_df, by = c("Disease", "pathway")) %>%
  dplyr::mutate(
    n_configs_hit = tidyr::replace_na(n_configs_hit, 0L),
    best_fdr = tidyr::replace_na(best_fdr, 1),
    median_fdr = tidyr::replace_na(median_fdr, 1),
    mean_fdr = tidyr::replace_na(mean_fdr, 1),
    best_score = tidyr::replace_na(best_score, 0),
    mean_score = tidyr::replace_na(mean_score, 0),
    max_NumLVsTopN = tidyr::replace_na(max_NumLVsTopN, 0),
    max_NumSamplesTopN = tidyr::replace_na(max_NumSamplesTopN, 0),
    max_RepRateLVsTopN = tidyr::replace_na(max_RepRateLVsTopN, 0),
    max_RepRateSamplesTopN = tidyr::replace_na(max_RepRateSamplesTopN, 0),
    n_libraries = tidyr::replace_na(n_libraries, 0L),
    fdr_signal = tidyr::replace_na(fdr_signal, 0),
    support_rate = tidyr::replace_na(support_rate, 0),
    recurrence_factor = tidyr::replace_na(recurrence_factor, 0),
    intensity_raw = tidyr::replace_na(intensity_raw, 0),
    intensity_capped = tidyr::replace_na(intensity_capped, 0)
  )

path_heat_mat <- path_heat_df %>%
  dplyr::select(Disease, pathway, intensity_capped) %>%
  tidyr::pivot_wider(names_from = pathway, values_from = intensity_capped) %>%
  dplyr::arrange(Disease)

path_row_names <- path_heat_mat$Disease
path_heat_mat_num <- path_heat_mat %>% dplyr::select(-Disease) %>% as.matrix()
rownames(path_heat_mat_num) <- path_row_names

if (ncol(path_heat_mat_num) > 1) {
  path_col_hc <- stats::hclust(stats::dist(t(path_heat_mat_num)), method = "ward.D2")
  path_col_order <- colnames(path_heat_mat_num)[path_col_hc$order]
  path_col_avg <- colMeans(path_heat_mat_num[, path_col_order, drop = FALSE], na.rm = TRUE)
  if (mean(path_col_avg[1:min(3, length(path_col_avg))], na.rm = TRUE) > mean(tail(path_col_avg, min(3, length(path_col_avg))), na.rm = TRUE)) {
    path_col_order <- rev(path_col_order)
  }
} else {
  path_col_order <- colnames(path_heat_mat_num)
}

path_row_score_df <- path_heat_df %>%
  dplyr::group_by(Disease) %>%
  dplyr::summarise(avg_heat = mean(intensity_capped, na.rm = TRUE), max_heat = max(intensity_capped, na.rm = TRUE), total_heat = sum(intensity_capped, na.rm = TRUE), total_hits = sum(n_configs_hit, na.rm = TRUE), .groups = "drop") %>%
  dplyr::arrange(avg_heat, max_heat, total_heat, total_hits)

path_row_order <- path_row_score_df$Disease

path_heat_df <- path_heat_df %>% dplyr::mutate(Disease = factor(Disease, levels = path_row_order), pathway = factor(pathway, levels = path_col_order))
path_peak_df <- path_heat_df %>% dplyr::group_by(Disease) %>% dplyr::slice_max(order_by = intensity_capped, n = 1, with_ties = FALSE) %>% dplyr::ungroup()
path_heat_df <- path_heat_df %>% dplyr::mutate(label_text = ifelse(n_configs_hit > 0, as.character(n_configs_hit), ""), label_color = ifelse(intensity_capped >= stats::quantile(intensity_capped, 0.72, na.rm = TRUE), "black", "white"))
path_top_df <- path_heat_df %>% dplyr::group_by(pathway) %>% dplyr::summarise(total_pathway_hits = sum(n_configs_hit, na.rm = TRUE), .groups = "drop") %>% dplyr::mutate(pathway = factor(pathway, levels = path_col_order))
path_right_df <- path_heat_df %>% dplyr::group_by(Disease) %>% dplyr::summarise(total_pathway_hits = sum(n_configs_hit, na.rm = TRUE), .groups = "drop") %>% dplyr::mutate(Disease = factor(Disease, levels = path_row_order))

pathway_label_map <- tibble(pathway = path_col_order, pathway_short = shorten_pathway_name(path_col_order, width = TRUNCATE_LABEL_TO))
if (USE_SHORT_PATHWAY_IDS) {
  pathway_label_map <- pathway_label_map %>% dplyr::mutate(pathway_display = paste0(SHORT_ID_PREFIX, seq_len(dplyr::n())), pathway_key = paste0(pathway_display, " = ", pathway))
} else {
  pathway_label_map <- pathway_label_map %>% dplyr::mutate(pathway_display = pathway_short, pathway_key = pathway)
}

path_heat_df <- path_heat_df %>% dplyr::left_join(pathway_label_map, by = "pathway")
path_top_df <- path_top_df %>% dplyr::left_join(pathway_label_map, by = "pathway")
path_peak_df <- path_peak_df %>% dplyr::left_join(pathway_label_map, by = "pathway")
readr::write_csv(pathway_label_map, paste0(out_prefix, "_pathway_label_key.csv"))

p_path_heat <- ggplot2::ggplot(path_heat_df, ggplot2::aes(x = pathway_display, y = Disease, fill = intensity_capped)) +
  ggplot2::geom_tile(color = "white", linewidth = 0.55) +
  ggplot2::geom_tile(data = path_peak_df, fill = NA, color = "white", linewidth = 1.0) +
  ggplot2::geom_text(ggplot2::aes(label = label_text, color = label_color), size = 2.6, fontface = "bold", show.legend = FALSE) +
  ggplot2::scale_color_identity() +
  viridis::scale_fill_viridis(option = "magma", direction = 1, name = "Pathway relevance\nscore", labels = scales::label_number(accuracy = 0.01)) +
  ggplot2::labs(title = "d  Disease-relevant pathway capture across diseases", subtitle = "Color reflects pathway-relevance intensity; numbers show recovered configurations.", x = if (USE_SHORT_PATHWAY_IDS) "Pathway (see exported key)" else "Pathway", y = "Disease", caption = if (USE_SHORT_PATHWAY_IDS) "Pathways are shown with short IDs to improve readability; the full pathway key is exported separately." else "Rows progress from lower to higher pathway-relevance intensity.") +
  theme_journal() +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, hjust = 1, vjust = 0.5, size = 7.8), legend.position = "right")

p_path_top <- ggplot2::ggplot(path_top_df, ggplot2::aes(x = pathway_display, y = total_pathway_hits)) +
  ggplot2::geom_col(width = 0.72, fill = "#666666") +
  ggplot2::geom_text(ggplot2::aes(label = total_pathway_hits), vjust = -0.22, size = 2.7) +
  ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = c(0, 0.10)), breaks = scales::pretty_breaks(n = 4)) +
  ggplot2::labs(title = "e  Total disease-relevant pathways captured by pathway", subtitle = "Summed across diseases.", x = NULL, y = "Configuration hits") +
  theme_journal() +
  ggplot2::theme(axis.text.x = ggplot2::element_blank(), axis.ticks.x = ggplot2::element_blank())

p_path_right <- ggplot2::ggplot(path_right_df, ggplot2::aes(x = total_pathway_hits, y = Disease)) +
  ggplot2::geom_col(width = 0.72, fill = "#666666") +
  ggplot2::geom_text(ggplot2::aes(label = total_pathway_hits), hjust = -0.08, size = 2.7) +
  ggplot2::scale_x_continuous(expand = ggplot2::expansion(mult = c(0, 0.10)), breaks = scales::pretty_breaks(n = 4)) +
  ggplot2::labs(title = "f  Total disease-relevant pathways captured by disease", subtitle = "Summed across pathways.", x = "Configuration hits", y = NULL) +
  theme_journal() +
  ggplot2::theme(axis.text.y = ggplot2::element_blank(), axis.ticks.y = ggplot2::element_blank())

path_left_block <- p_path_top / p_path_heat + patchwork::plot_layout(heights = c(0.82, 1.88))
path_block <- path_left_block | p_path_right + patchwork::plot_layout(widths = c(1.9, 1.05), guides = "collect")

final_plot <- gene_block / path_block + patchwork::plot_layout(heights = c(1, 1), guides = "collect") & ggplot2::theme(legend.position = "right", plot.background = ggplot2::element_rect(fill = "white", colour = NA), plot.margin = ggplot2::margin(1, 1, 1, 1))

print(final_plot)

pdf_device_to_use <- if (capabilities("cairo")) cairo_pdf else "pdf"

ggplot2::ggsave(filename = paste0(out_prefix, ".pdf"), plot = final_plot, width = 15.5, height = 15.6, units = "in", dpi = 600, device = pdf_device_to_use, bg = "white")
ggplot2::ggsave(filename = paste0(out_prefix, ".png"), plot = final_plot, width = 15.5, height = 15.6, units = "in", dpi = 600, bg = "white")
ggplot2::ggsave(filename = paste0(out_prefix, ".tiff"), plot = final_plot, width = 15.5, height = 15.6, units = "in", dpi = 600, compression = "lzw", bg = "white")

readr::write_csv(
  gene_heat_df %>% dplyr::select(Disease, LV_label, n_disgenet_genes, total_disgenet_genes_for_disease, capture_fraction, weighted_fraction, heat_value),
  paste0(out_prefix, "_gene_heatmap_summary.csv")
)

readr::write_csv(
  path_heat_df %>% dplyr::select(Disease, pathway, pathway_display, n_configs_hit, best_fdr, median_fdr, mean_fdr, best_score, mean_score, max_NumLVsTopN, max_NumSamplesTopN, max_RepRateLVsTopN, max_RepRateSamplesTopN, n_libraries, intensity_raw, intensity_capped),
  paste0(out_prefix, "_pathway_heatmap_summary.csv")
)
